/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "libdazzle-1.0"

#define LOCALEDIR "/usr/local/share/locale"

#define _DZL_EXTERN __attribute__((visibility("default"))) extern

